name: face_id_plus
version: 7.5.0
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  cached_network_image: any
  camera: any
  carousel_slider: any
  charts_flutter: ^0.12.0
  connectivity: any
  convex_bottom_bar: ^3.0.0
  cupertino_icons: any
  dart_ping: any
  dropdown_button2: any
  equatable: any
  ffi: any
  firebase_core: any
  firebase_messaging: any
  flutter:
    sdk: flutter
  flutter_bloc: any
  flutter_datetime_picker:
    git: https://github.com/Realank/flutter_datetime_picker.git
  flutter_launcher_icons: ^0.9.3
  flutter_lints: ^2.0.1
  flutter_local_notifications: any
  flutter_slidable: any
  geolocator: any
  get: ^4.6.5
  google_maps_flutter: ^2.1.8
  http: ^0.13.4
  image: any
  image_picker: any
  internet_connection_checker: any
  intl: any
  intro_slider: any
  lazy_load_scrollview: any
  location: ^4.3.0
  network_info_plus: any
  path_provider: any
  permission_handler: any
  platform_device_id: any
  provider: any
  pull_to_refresh: any
  rounded_loading_button: any
  shared_preferences: any
  socket_io_client: any
  sqflite: any
  table_calendar: any
  timer_builder: any
  uuid: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path_android: assets/icabp.png
  image_path_ios: assets/icabp.png
  android: true
  ios: true
  remove_alpha_ios: true

flutter:
  assets:
    - assets/images/abp.png
    - assets/images/dev.png
    - assets/images/ic_abp.png
    - assets/images/abp_60x60.png
    - assets/images/abp_maps.png
    - assets/images/abp_ic.png
    - assets/images/sarana.png
    - assets/images/sarana_add.png
    - assets/images/ob.png
    - assets/images/crushing.png
    - assets/images/hauling.png
    - assets/images/product_stock.png
    - assets/images/stock.png
    - assets/images/total_rkb.png
    - assets/images/appr_rkb.png
    - assets/images/cancel_rkb.png
    - assets/images/close_rkb.png
    - assets/images/waiting_rkb.png
    - assets/ic_abp.png
    - assets/icabp.png
    - assets/images/new_user.png
    - assets/images/login_ic.png
    - assets/images/car_ic.png
    - assets/images/mine_permit.psd
    - assets/images/SIMPER_ABP.psd
  uses-material-design: true
