part of 'app_pages.dart';

abstract class Routes {
  Routes._();
  static const HOME = _Paths.HOME;
  static const LOGIN = _Paths.LOGIN;
  static const LOGIN_ABSEN = _Paths.LOGIN_ABSEN;
  static const BULETIN = _Paths.BULETIN;
  static const ABSENSI = _Paths.ABSENSI;
  static const MENU_ABP = _Paths.MENU_ABP;
  static const SPLASH = _Paths.SPLASH;
  static const KAMERA = _Paths.KAMERA;
  static const LOKASI = _Paths.LOKASI;
  static const PENIMPANAN = _Paths.PENIMPANAN;
  static const NOTIFIKASI = _Paths.NOTIFIKASI;
  static const GALERY = _Paths.GALERY;
  static const PROFILE = _Paths.PROFILE;
  static const MAIN_ABSEN = _Paths.MAIN_ABSEN;
  static const ABSENSI_V_P_S = _Paths.ABSENSI_V_P_S;
  static const LIST_ABSEN = _Paths.LIST_ABSEN;
  static const ROSTER_KERJA = _Paths.ROSTER_KERJA;
  static const GRAFIK_KEHADIRAN = _Paths.GRAFIK_KEHADIRAN;
  static const ABSEN_MASUK = _Paths.ABSEN_MASUK;
  static const ABSEN_PULANG = _Paths.ABSEN_PULANG;
  static const CORRECTIVE_ACTION = _Paths.CORRECTIVE_ACTION;
  static const PROFILE_ABP = _Paths.PROFILE_ABP;
  static const HAZARD_LIST = _Paths.HAZARD_LIST;
  static const DETAIL_HAZARD = _Paths.DETAIL_HAZARD;
  static const RUBAH_HAZARD = _Paths.RUBAH_HAZARD;
  static const IMAGE_HAZARD_VIEW = _Paths.IMAGE_HAZARD_VIEW;
  static const HAZARD_USER = _Paths.HAZARD_USER;
  static const HAZARD_P_J = _Paths.HAZARD_P_J;
  static const FORM_HAZARD = _Paths.FORM_HAZARD;
  static const LIST_USER = _Paths.LIST_USER;
  static const KEMUNGKINAN = _Paths.KEMUNGKINAN;
  static const KEPARAHAN = _Paths.KEPARAHAN;
  static const PENGENDALIAN = _Paths.PENGENDALIAN;
  static const LOKASI_HAZARD = _Paths.LOKASI_HAZARD;
  static const PERUSAHAAN = _Paths.PERUSAHAAN;
}

abstract class _Paths {
  _Paths._();
  static const HOME = '/home';
  static const LOGIN = '/login';
  static const LOGIN_ABSEN = '/login-absen';
  static const BULETIN = '/buletin';
  static const ABSENSI = '/absensi';
  static const MENU_ABP = '/menu-abp';
  static const SPLASH = '/splash';
  static const KAMERA = '/kamera';
  static const LOKASI = '/lokasi';
  static const PENIMPANAN = '/penimpanan';
  static const NOTIFIKASI = '/notifikasi';
  static const GALERY = '/galery';
  static const PROFILE = '/profile';
  static const MAIN_ABSEN = '/main-absen';
  static const ABSENSI_V_P_S = '/absensi-v-p-s';
  static const LIST_ABSEN = '/list-absen';
  static const ROSTER_KERJA = '/roster-kerja';
  static const GRAFIK_KEHADIRAN = '/grafik-kehadiran';
  static const ABSEN_MASUK = '/absen-masuk';
  static const ABSEN_PULANG = '/absen-pulang';
  static const CORRECTIVE_ACTION = '/corrective-action';
  static const PROFILE_ABP = '/profile-abp';
  static const HAZARD_LIST = '/hazard-list';
  static const DETAIL_HAZARD = '/detail-hazard';
  static const RUBAH_HAZARD = '/rubah-hazard';
  static const IMAGE_HAZARD_VIEW = '/image-hazard-view';
  static const HAZARD_USER = '/hazard-user';
  static const HAZARD_P_J = '/hazard-p-j';
  static const HSE = '/hse';
  static const FORM_HAZARD = '/form-hazard';
  static const LIST_USER = '/list-user';
  static const KEMUNGKINAN = '/kemungkinan';
  static const KEPARAHAN = '/keparahan';
  static const PENGENDALIAN = '/pengendalian';
  static const LOKASI_HAZARD = '/lokasi-hazard';
  static const PERUSAHAAN = '/perusahaan';
}
